### ISSUE TITLE
Credential title in wallet is based on the schema name instead of the credential defenition name

### ISSUE THREAD

**Issue by wadeking98** [bcgov/bc-wallet-mobile-sch-holder#59]
In BC Wallet, when accepting a credential, the credential title is created from the schema name. 
It is more conventional to use the credential definition name as the title rather than the schema name.

Steps to reproduce issue:
- Download the BC Wallet Demo and replace the `Student Card` credential defenition with something like `Student Card DEV` in the CredDefService.ts file
- Replace references to `Student Card` with `Student Card DEV` in the demo use cases
- Populate the .env files in the server and client folders. (Need openshift access to see the DID Seed)
- Start the demo and accept a credential  
  
Issue: The Credential title will be `Student Card` instead of the expected `Student Card DEV`

**Comment by swcurran** [comment]
I think this is a bad idea unless this is what other wallets are doing.  At minimum, you should check what esatus, LISSI and Trinsic are doing.

**Comment by wadeking98** [comment]
I did some testing and I found that both lissi and esatus use the name of the credential definition. Trinsic uses the name of the schema like we do right now

**Comment by wadeking98** [comment]
Basically my reasoning is that we can expect there to be multiple credential definitions for a single schema (for example: a canadian driver's license schema and then a credential definition for a BC, Ontario, etc driver's license that uses that schema). Right now our wallet would display `Canadian Drivers License` (from the schema) instead of `BC Driver's License` (from the credential definition)

**Comment by amanji** [comment]
This repo is for the now defunct BC Wallet for the Smart Health Card (vaccine card holder). This issue should be transferred to the BC Wallet Mobile repo. I’d further suggest we archive this repo.
